export const cartTypes = {
    CART_UPDATE_REQUEST: 'CART_UPDATE_REQUEST',
    CART_UPDATE_SUCCESS: 'CART_UPDATE_SUCCESS',
    CART_UPDATE_FAILURE: 'CART_UPDATE_FAILURE',


    ADD_CART_REQUEST: 'ADD_CART_REQUEST',
    ADD_CART_SUCCESS: 'ADD_CART_SUCCESS',
    ADD_CART_FAILURE: 'ADD_CART_FAILURE',

    GETALL_CART_REQUEST: 'GETALL_CART_REQUEST',
    GETALL_CART_SUCCESS: 'GETALL_CART_SUCCESS',
    GETALL_CART_FAILURE: 'GETALL_CART_FAILURE',

    DELETE_FROM_CART_REQUEST: 'DELETE_FROM_CART_REQUEST',
    DELETE_FROM_CART_SUCCESS: 'DELETE_FROM_CART_SUCCESS',
    DELETE_FROM_CART_FAILURE: 'DELETE_FROM_CART_FAILURE',


};
