export const sleeve_condition_prodTypes = {

    GETALL_REQUEST: 'SLEEVE_CONDITION_GETALL_REQUEST',
    GETALL_SUCCESS: 'SLEEVE_CONDITION_GETALL_SUCCESS',
    GETALL_FAILURE: 'SLEEVE_CONDITION_GETALL_FAILURE',


};
